/** Palavras do jogo, com grafia e acentuação corretas. */
export const listaDePalavras = [
  'CAMPO','TEMPO','LIMPO','COMPRA','TAMPA','COMPRIDO','EMPREGO','SIMPLES','COMPUTADOR','LAMPIÃO','AMPLO','COMPANHEIRO','CUMPRIR','ESTAMPA','OLIMPÍADA','SIMPATIA','TEMPERO','ACOMPANHAR','EXEMPLO','IMPACTO','INTERROMPER','LIMPEZA','PASSATEMPO','RELÂMPAGO','ACAMPAMENTO','CAMPEÃO','CAMPAINHA','LÂMPADA','TROMPETE','IMPRIMIR','EMPADA','EMPURRAR','SEMPRE','TEMPESTADE','COMPLETO','IMPORTANTE','SIMPÁTICO','CAMPEONATO','EMPRESTAR','LIMPAR','RAMPA','TEMPERATURA','AMPARO','CHIMPANZÉ','COMPARTILHAR','EMPINAR','COMPASSO','IMPÉRIO',
  'BOMBA','SAMBA','POMBA','EMBAIXO','BOMBEIRO','ZUMBIDO','AMBULÂNCIA','EMBORA','MEMBRO','SOMBRA','TROMBONE','SÍMBOLO','TAMBOR','UMBIGO','COMBOIO','IMBATÍVEL','LOMBADA','REEMBOLSO','EMBLEMA','COMBUSTÍVEL','AMBOS','SETEMBRO','NOVEMBRO','DEZEMBRO','COMBINAR','LAMBER','TAMBÉM','CAMBALHOTA','GAMBÁ','TOMBO','EMBRULHO','TIMBRE','BAMBU','SOMBRINHA','COMBATE','LOMBO','ZUMBI','TROMBADA',
  'TINTA','PENTE','ONDA','BANCO','MUNDO','VENTO','SANTO','CONTA','PONTE','ELEFANTE','DENTE','GENTE','ONZE','FUNDO','LINDO','LONGE','MANGA','GANSO','ONÇA','PINCEL','BANDA','CRIANÇA','DANÇA','ESTANTE','GIGANTE','JANTAR','LANCHA','MORANGO','NUNCA','PANDA','PRESENTE','SEGUNDA','TANQUE','TRANQUILO','VINTE','CONVITE','ENCONTRAR','FANTASMA','INSTRUMENTO','LARANJA','MANTIMENTO','INGLÊS','CONSTRUIR','INSTANTE','MENDIGO','TANGERINA','TRANSPORTE','MENSAGEM','PENSAR','CENTRO','CONCHA','INJEÇÃO','CANTAR','ANTES','CINCO','ONTEM','DOMINGO','CANGURU','PINGUIM','MENTIRA','CONTENTE','ANTENA','BRINCAR','CANSADO','DENTISTA','FONTE','GARGANTA','INVENTOR','LANTERNA','MANTEIGA','QUINTAL','SANDÁLIA','TONTO','VONTADE','PINTAR','MONTANHA','CANTIGA','ENCANTO',
];

/** Devolve a lacuna pedagógica e a letra que a completa. */
export function gerarLacuna(palavra) {
  let indice = palavra.search(/M(?=[PB])/);
  if (indice === -1) indice = palavra.search(/N(?=[^AEIOUÁÉÍÓÚÂÊÔÃÕ])/);
  if (indice === -1) throw new Error(`Palavra sem M/N antes de consoante: ${palavra}`);
  return {
    texto: `${palavra.slice(0, indice)}_${palavra.slice(indice + 1)}`,
    resposta: palavra[indice],
    indice,
  };
}
