import { montarCabecalho } from '../../shared/cabecalho.js';import { animar,lancarConfete } from '../../shared/confete.js';import { calcularEstrelas,nomeDaCrianca,obterConfiguracoes,registrarPartida } from '../../shared/progresso.js';import { tocar } from '../../shared/sons.js';import { conferirDados,conferirOrdem,montarPecas,montarRodada } from './jogo.js';
montarCabecalho('Forme a Palavra');const problemas=conferirDados();if(problemas.length)throw new Error(problemas.join('\n'));const $=id=>document.getElementById(id);let nivel=3,rodada=[],indice=0,acertos=0,erros=0,item,disponiveis=[],montadas=[],respondendo=false,inicio=0,intervalo=null;
function exibir(id){['inicio','partida','final'].forEach(t=>$(t).hidden=t!==id)}function selecionar(valor){nivel=Number(valor);document.querySelectorAll('[data-nivel]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.nivel)===nivel)))}document.querySelectorAll('[data-nivel]').forEach(b=>b.addEventListener('click',()=>selecionar(b.dataset.nivel)));const nivelSalvo=Number(obterConfiguracoes().niveis['forme-palavra']);selecionar([1,2,3].includes(nivelSalvo)?nivelSalvo:3);
function botaoPeca(peca,origem){const b=document.createElement('button');b.className='botao peca';b.textContent=peca.texto;b.setAttribute('aria-label',`${origem==='linha'?'Retirar':'Usar'} sílaba ${peca.texto}`);b.addEventListener('click',()=>origem==='linha'?devolver(peca):usar(peca));return b}function renderizar(){ $('linha').replaceChildren(...montadas.map(p=>botaoPeca(p,'linha')));$('pecas').replaceChildren(...disponiveis.map(p=>botaoPeca(p,'pecas')))}
function mostrar(){respondendo=false;item=rodada[indice];disponiveis=montarPecas(item);montadas=[];$('atual').textContent=indice+1;$('progresso').value=indice;$('emoji').textContent=item.emoji;$('feedback').textContent='';$('feedback').className='feedback';renderizar()}
function usar(peca){if(respondendo)return;tocar('clique');disponiveis=disponiveis.filter(p=>p.id!==peca.id);montadas.push(peca);renderizar();if(montadas.length===item.silabas.length)conferir()}
function devolver(peca){if(respondendo)return;montadas=montadas.filter(p=>p.id!==peca.id);disponiveis.push(peca);renderizar();tocar('clique')}
function conferir(){respondendo=true;if(conferirOrdem(item,montadas)){acertos++;$('acertos').textContent=acertos;$('feedback').textContent=`Muito bem! ${item.palavra}`;$('feedback').className='feedback feedback--certo palavra-certa';tocar('acerto');animar($('linha'),'pular');setTimeout(avancar,900)}else{erros++;$('erros').textContent=erros;$('feedback').textContent='Essa ordem não formou a palavra. Tente outra vez!';$('feedback').className='feedback feedback--errado';tocar('erro');animar($('linha'),'tremer');setTimeout(()=>{disponiveis=[...disponiveis,...montadas];montadas=[];respondendo=false;renderizar()},900)}}
function avancar(){indice++;$('progresso').value=indice;indice>=rodada.length?finalizar():mostrar()}function tempo(){const s=Math.floor((Date.now()-inicio)/1000);$('tempo').textContent=`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function iniciar(){rodada=montarRodada(nivel);indice=0;acertos=0;erros=0;$('acertos').textContent='0';$('erros').textContent='0';inicio=Date.now();clearInterval(intervalo);intervalo=setInterval(tempo,1000);tempo();exibir('partida');mostrar();tocar('clique')}
function finalizar(){clearInterval(intervalo);const estrelas=calcularEstrelas(acertos,erros);registrarPartida('forme-palavra',{acertos,erros,estrelas});$('resumo').textContent=`${nomeDaCrianca()}, você formou ${acertos} palavras e fez ${erros} tentativa${erros===1?'':'s'} incorreta${erros===1?'':'s'}.`;$('estrelas').textContent='⭐'.repeat(estrelas);exibir('final');tocar('vitoria');lancarConfete()}
$('comecar').addEventListener('click',iniciar);$('sair').addEventListener('click',()=>{clearInterval(intervalo);exibir('inicio')});$('de-novo').addEventListener('click',iniciar);$('trocar').addEventListener('click',()=>exibir('inicio'));
