const q=(pergunta,correta,erradas,explicacao,emoji='💡')=>({pergunta,correta,opcoes:[correta,...erradas],explicacao,emoji});
export const categorias=Object.freeze({
ciencias:{nome:'Ciências',emoji:'🔬',perguntas:[
q('Qual astro ilumina a Terra?','O Sol',['A Lua','Marte','Vênus'],'O Sol é a estrela mais próxima da Terra.','☀️'),
q('Em que estado a água vira gelo?','Sólido',['Líquido','Gasoso','Plasma'],'O gelo é água no estado sólido.','🧊'),
q('Como se chama a passagem da água líquida para vapor?','Evaporação',['Condensação','Solidificação','Fusão'],'Na evaporação, a água líquida passa ao estado gasoso.','💧'),
q('Como se chama a passagem do vapor para líquido?','Condensação',['Evaporação','Fusão','Sublimação'],'A condensação forma gotinhas a partir do vapor.','🌧️'),
q('Qual gás usamos principalmente na respiração?','Oxigênio',['Hélio','Hidrogênio','Neônio'],'Nosso corpo usa oxigênio para obter energia dos alimentos.','🫁'),
q('Qual parte da planta absorve água do solo?','Raiz',['Flor','Fruto','Folha'],'As raízes absorvem água e sais minerais.','🌱'),
q('Qual processo permite que plantas produzam alimento usando luz?','Fotossíntese',['Respiração','Digestão','Fermentação'],'Na fotossíntese, plantas usam luz, água e gás carbônico.','🌿'),
q('Que força nos mantém no chão?','Gravidade',['Magnetismo','Atrito','Eletricidade'],'A gravidade atrai os corpos em direção à Terra.','🌍'),
q('Qual material é atraído por um ímã comum?','Ferro',['Madeira','Vidro','Papel'],'Ímãs comuns atraem materiais como ferro e aço.','🧲'),
q('O som consegue viajar no vácuo?','Não',['Sim, mais rápido','Só à noite','Apenas som grave'],'O som precisa de um meio, como ar, água ou sólido.','🔊'),
q('A que temperatura a água pura congela, aproximadamente?','0 °C',['10 °C','50 °C','100 °C'],'Na escala Celsius, a água congela perto de 0 °C.','🌡️'),
q('A que temperatura a água ferve ao nível do mar?','100 °C',['0 °C','50 °C','200 °C'],'Ao nível do mar, água pura ferve perto de 100 °C.','♨️'),
q('Qual fonte de energia é renovável?','Luz solar',['Carvão mineral','Petróleo','Gás natural'],'A luz do Sol se renova naturalmente.','🔆'),
q('Qual destes é um bom condutor de eletricidade?','Cobre',['Borracha','Plástico','Madeira seca'],'O cobre é muito usado em fios elétricos.','⚡'),
q('Quantas cores são tradicionalmente reconhecidas no arco-íris?','Sete',['Três','Cinco','Doze'],'A divisão tradicional apresenta sete cores.','🌈'),
q('Qual instrumento mede a temperatura?','Termômetro',['Balança','Régua','Bússola'],'O termômetro mede temperatura.','🌡️'),
q('Animais com coluna vertebral são chamados de quê?','Vertebrados',['Invertebrados','Decompositores','Produtores'],'Vertebrados possuem coluna vertebral.','🦴'),
q('Qual destes ajuda a decompor matéria na natureza?','Fungo',['Pedra','Plástico','Vidro'],'Muitos fungos decompõem restos de seres vivos.','🍄'),
q('O que acontece com a sombra quando bloqueamos a luz?','Forma uma região menos iluminada',['Produz som','Aumenta a temperatura sempre','Cria vento'],'A sombra surge onde a luz é bloqueada.','🔦'),
q('Qual é a principal fonte de energia para a vida na Terra?','O Sol',['A Lua','O vento','As rochas'],'A maior parte das cadeias alimentares começa com energia solar.','☀️'),
q('Qual mistura tem água como solvente?','Água com sal dissolvido',['Areia com pedras','Feijão com arroz','Óleo com areia'],'Na água salgada, a água dissolve o sal.','🧂'),
q('Qual estado da matéria tem forma própria?','Sólido',['Líquido','Gasoso','Vapor'],'Um sólido conserva sua forma em condições comuns.','🧱'),
q('Qual estado da matéria ocupa todo o recipiente disponível?','Gasoso',['Sólido','Líquido apenas','Cristalino'],'Um gás se espalha pelo recipiente.','🎈'),
q('A Lua produz a luz que vemos?','Não, ela reflete a luz do Sol',['Sim, produz luz própria','Só durante a lua cheia','Só no verão'],'A Lua é iluminada pelo Sol e reflete parte dessa luz.','🌙'),
q('Como se chama o transporte de pólen entre flores?','Polinização',['Germinação','Evaporação','Erosão'],'A polinização leva pólen até a parte reprodutiva da flor.','🐝'),
]},
animais:{nome:'Animais',emoji:'🐾',perguntas:[
q('Qual é o maior animal do planeta?','Baleia-azul',['Elefante-africano','Girafa','Tubarão-branco'],'A baleia-azul é o maior animal conhecido.','🐋'),
q('Qual é o maior animal terrestre?','Elefante-africano',['Hipopótamo','Girafa','Rinoceronte'],'O elefante-africano é o maior animal que vive em terra.','🐘'),
q('Qual mamífero põe ovos?','Ornitorrinco',['Golfinho','Morcego','Macaco'],'O ornitorrinco é um mamífero monotremado e põe ovos.','🥚'),
q('Qual animal passa por metamorfose de lagarta para adulto?','Borboleta',['Aranha','Minhoca','Lagarto'],'A lagarta forma uma pupa e se transforma em borboleta.','🦋'),
q('Quantas patas tem uma aranha?','Oito',['Seis','Quatro','Dez'],'Aranhas são aracnídeos e têm oito patas.','🕷️'),
q('Quantas patas tem um inseto adulto?','Seis',['Oito','Quatro','Dez'],'Insetos adultos possuem três pares de patas.','🐜'),
q('Qual ave não voa e vive naturalmente na Antártida?','Pinguim',['Avestruz','Ema','Tucano'],'Há espécies de pinguins que vivem na Antártida.','🐧'),
q('Qual animal usa ecolocalização para se orientar?','Morcego',['Girafa','Tartaruga','Galinha'],'Muitos morcegos emitem sons e interpretam os ecos.','🦇'),
q('Qual destes respira por brânquias durante toda a vida?','Peixe',['Golfinho','Baleia','Tartaruga-marinha'],'Peixes retiram oxigênio da água pelas brânquias.','🐟'),
q('Qual destes é um anfíbio?','Sapo',['Lagarto','Galinha','Coelho'],'Sapos passam parte do ciclo de vida na água e parte em terra.','🐸'),
q('Qual destes é um réptil?','Cobra',['Sapo','Morcego','Pinguim'],'Cobras pertencem ao grupo dos répteis.','🐍'),
q('Qual é o animal terrestre mais alto?','Girafa',['Elefante','Camelo','Avestruz'],'A girafa alcança a maior altura entre animais terrestres.','🦒'),
q('O que as abelhas coletam nas flores?','Néctar e pólen',['Pedras e areia','Folhas secas','Água salgada'],'Abelhas visitam flores para obter néctar e pólen.','🐝'),
q('Qual animal constrói barragens?','Castor',['Coala','Guepardo','Panda'],'Castores usam galhos e lama para construir barragens.','🦫'),
q('Qual destes é um marsupial?','Canguru',['Cavalo','Urso-polar','Lobo'],'Filhotes de canguru completam o desenvolvimento na bolsa.','🦘'),
q('Qual animal tem listras pretas e brancas?','Zebra',['Girafa','Onça-pintada','Leopardo'],'Cada zebra tem um padrão próprio de listras.','🦓'),
q('Qual destes animais é herbívoro?','Coelho',['Leão','Águia','Tubarão'],'Coelhos se alimentam principalmente de plantas.','🐰'),
q('Qual destes animais é carnívoro?','Leão',['Vaca','Girafa','Capivara'],'Leões se alimentam de outros animais.','🦁'),
q('Como se chama o filhote da galinha?','Pintinho',['Bezerro','Potro','Cordeiro'],'O filhote da galinha é o pintinho.','🐥'),
q('Como se chama um grupo de peixes?','Cardume',['Alcateia','Manada','Enxame'],'Cardume é um conjunto de peixes.','🐟'),
q('Como se chama um grupo de lobos?','Alcateia',['Cardume','Colmeia','Rebanho'],'Um grupo de lobos é chamado de alcateia.','🐺'),
q('Qual animal tem uma carapaça e anda lentamente?','Tartaruga',['Polvo','Golfinho','Papagaio'],'Tartarugas protegem o corpo com uma carapaça.','🐢'),
q('Qual destes animais é um molusco com oito braços?','Polvo',['Caranguejo','Estrela-do-mar','Água-viva'],'Polvos são moluscos e possuem oito braços.','🐙'),
q('Qual felino brasileiro tem manchas em forma de roseta?','Onça-pintada',['Lobo-guará','Tamanduá','Capivara'],'A onça-pintada tem pelagem com manchas chamadas rosetas.','🐆'),
q('Qual animal brasileiro se alimenta principalmente de formigas?','Tamanduá',['Arara','Capivara','Boto'],'O tamanduá usa a língua comprida para capturar formigas e cupins.','🐜'),
]},
brasil:{nome:'Brasil',emoji:'🇧🇷',perguntas:[
q('Qual é a capital do Brasil?','Brasília',['Rio de Janeiro','São Paulo','Salvador'],'Brasília é a capital federal desde 1960.','🏛️'),
q('Qual é o idioma oficial do Brasil?','Português',['Espanhol','Inglês','Francês'],'A Constituição define o português como idioma oficial.','🗣️'),
q('Qual é a moeda oficial brasileira?','Real',['Peso','Euro','Dólar'],'A moeda do Brasil é o real.','💰'),
q('Quantas grandes regiões o Brasil tem?','Cinco',['Três','Seis','Oito'],'São Norte, Nordeste, Centro-Oeste, Sudeste e Sul.','🗺️'),
q('Qual é o maior estado brasileiro em área?','Amazonas',['Bahia','Minas Gerais','Pará'],'O Amazonas é o estado de maior área.','🌳'),
q('Qual é o menor estado brasileiro em área?','Sergipe',['Alagoas','Espírito Santo','Acre'],'Sergipe é o menor estado em extensão territorial.','📍'),
q('Em que região fica o estado do Amazonas?','Norte',['Sul','Sudeste','Nordeste'],'O Amazonas pertence à Região Norte.','🧭'),
q('Em que região fica o Rio Grande do Sul?','Sul',['Norte','Centro-Oeste','Nordeste'],'O Rio Grande do Sul é um dos três estados da Região Sul.','🧭'),
q('Em que região fica Minas Gerais?','Sudeste',['Norte','Sul','Centro-Oeste'],'Minas Gerais pertence à Região Sudeste.','🧭'),
q('Em que região fica a Bahia?','Nordeste',['Norte','Sul','Sudeste'],'A Bahia pertence à Região Nordeste.','🧭'),
q('Em que região fica Goiás?','Centro-Oeste',['Norte','Sul','Sudeste'],'Goiás pertence à Região Centro-Oeste.','🧭'),
q('Qual oceano banha o litoral brasileiro?','Atlântico',['Pacífico','Índico','Ártico'],'Todo o litoral brasileiro é banhado pelo Atlântico.','🌊'),
q('Em que data se comemora a Independência do Brasil?','7 de setembro',['21 de abril','15 de novembro','1º de maio'],'A Independência foi proclamada em 7 de setembro de 1822.','🇧🇷'),
q('Em que data se comemora a Proclamação da República?','15 de novembro',['7 de setembro','12 de outubro','21 de abril'],'A República foi proclamada em 15 de novembro de 1889.','📜'),
q('Qual cidade é conhecida pelo Cristo Redentor?','Rio de Janeiro',['Recife','Curitiba','Manaus'],'O Cristo Redentor fica no morro do Corcovado, no Rio.','🗽'),
q('Em qual estado ficam as Cataratas do Iguaçu?','Paraná',['Ceará','Amazonas','Goiás'],'As cataratas ficam em Foz do Iguaçu, no Paraná.','🏞️'),
q('Em qual estado ficam os Lençóis Maranhenses?','Maranhão',['Pará','Piauí','Bahia'],'O Parque Nacional dos Lençóis Maranhenses fica no Maranhão.','🏜️'),
q('O Pelourinho fica em qual cidade?','Salvador',['Belém','Porto Alegre','Brasília'],'O Pelourinho é um conjunto histórico de Salvador.','🏘️'),
q('Qual bioma ocupa grande parte da Região Norte?','Amazônia',['Pampa','Caatinga','Pantanal'],'A Amazônia predomina em grande parte do Norte.','🌴'),
q('Qual bioma é típico do sertão nordestino?','Caatinga',['Pampa','Pantanal','Mata de Araucárias'],'A Caatinga é adaptada ao clima semiárido.','🌵'),
q('Qual bioma de campos predomina no Rio Grande do Sul?','Pampa',['Amazônia','Caatinga','Pantanal'],'No Brasil, o Pampa ocorre no Rio Grande do Sul.','🌾'),
q('Qual grande área alagável fica principalmente em Mato Grosso e Mato Grosso do Sul?','Pantanal',['Pampa','Caatinga','Mata Atlântica'],'O Pantanal ocupa áreas desses dois estados.','🐊'),
q('Quais cores aparecem no fundo da bandeira do Brasil?','Verde e amarelo',['Azul e vermelho','Preto e branco','Roxo e laranja'],'A bandeira tem campo verde e losango amarelo.','🇧🇷'),
q('Qual frase aparece na bandeira brasileira?','Ordem e Progresso',['Pátria Amada','Brasil para Todos','União e Força'],'A faixa branca traz a frase Ordem e Progresso.','🇧🇷'),
q('Quantos estados o Brasil possui, sem contar o Distrito Federal?','26',['25','27','28'],'O Brasil tem 26 estados e um Distrito Federal.','🗺️'),
]},
corpo:{nome:'Corpo humano',emoji:'🫀',perguntas:[
q('Qual órgão bombeia o sangue?','Coração',['Pulmão','Estômago','Rim'],'O coração impulsiona o sangue pelo corpo.','❤️'),
q('Qual órgão usamos principalmente para respirar?','Pulmões',['Rins','Fígado','Intestinos'],'Os pulmões fazem trocas gasosas com o ar.','🫁'),
q('Qual órgão coordena pensamentos e movimentos?','Cérebro',['Estômago','Pâncreas','Bexiga'],'O cérebro integra informações e coordena muitas funções.','🧠'),
q('Onde começa a digestão dos alimentos?','Na boca',['No coração','Nos pulmões','Nos rins'],'Mastigação e saliva iniciam a digestão.','👄'),
q('Qual órgão mistura o alimento com o suco gástrico?','Estômago',['Coração','Bexiga','Traqueia'],'O estômago participa da digestão com movimentos e suco gástrico.','🫃'),
q('Qual é o maior órgão do corpo humano?','Pele',['Coração','Fígado','Cérebro'],'A pele reveste e protege todo o corpo.','🖐️'),
q('Quantos dentes costuma ter um adulto com dentição completa?','32',['20','24','40'],'A dentição adulta completa normalmente tem 32 dentes.','🦷'),
q('Quantos dentes de leite costuma ter uma criança?','20',['10','16','32'],'A dentição decídua completa normalmente tem 20 dentes.','🦷'),
q('Que parte do olho controla a quantidade de luz que entra?','Íris',['Retina','Pálpebra','Lágrima'],'A íris ajusta o tamanho da pupila.','👁️'),
q('Qual sentido está ligado ao nariz?','Olfato',['Visão','Audição','Tato'],'Receptores no nariz percebem odores.','👃'),
q('Qual sentido está ligado aos ouvidos?','Audição',['Paladar','Visão','Olfato'],'Os ouvidos captam vibrações sonoras.','👂'),
q('Qual sentido percebe sabores?','Paladar',['Tato','Audição','Visão'],'O paladar detecta substâncias dos alimentos.','👅'),
q('O esqueleto ajuda principalmente a fazer o quê?','Sustentar e proteger o corpo',['Produzir pensamentos','Digerir sozinho','Bombear sangue'],'O esqueleto dá sustentação e protege órgãos.','🦴'),
q('O que liga os músculos aos ossos?','Tendões',['Nervos','Veias','Cartilagens apenas'],'Tendões conectam músculos aos ossos.','💪'),
q('O que liga um osso a outro nas articulações?','Ligamentos',['Tendões','Cabelos','Unhas'],'Ligamentos ajudam a estabilizar articulações.','🦵'),
q('Quais células transportam principalmente oxigênio no sangue?','Glóbulos vermelhos',['Plaquetas','Neurônios','Células da pele'],'A hemoglobina dos glóbulos vermelhos transporta oxigênio.','🩸'),
q('Qual componente ajuda o sangue a coagular?','Plaquetas',['Saliva','Lágrimas','Neurônios'],'Plaquetas participam da formação do coágulo.','🩸'),
q('Quais órgãos filtram o sangue e produzem urina?','Rins',['Pulmões','Olhos','Ouvidos'],'Os rins retiram resíduos e excesso de água do sangue.','🫘'),
q('Onde a urina fica armazenada antes de sair?','Bexiga',['Estômago','Fígado','Pâncreas'],'A bexiga armazena a urina temporariamente.','💧'),
q('Qual tubo leva o ar da garganta aos pulmões?','Traqueia',['Esôfago','Uretra','Intestino'],'A traqueia conduz o ar até os brônquios.','🫁'),
q('Qual tubo leva alimento da garganta ao estômago?','Esôfago',['Traqueia','Artéria','Ureter'],'O esôfago conduz o alimento ao estômago.','🥪'),
q('Onde ocorre a maior parte da absorção de nutrientes?','Intestino delgado',['Boca','Intestino grosso','Bexiga'],'O intestino delgado absorve a maior parte dos nutrientes.','🍎'),
q('Qual órgão produz a bile?','Fígado',['Coração','Rim','Pulmão'],'O fígado produz bile, que auxilia na digestão de gorduras.','🫀'),
q('Por que suamos?','Para ajudar a resfriar o corpo',['Para aumentar a febre','Para produzir sangue','Para fortalecer ossos'],'A evaporação do suor ajuda a perder calor.','💦'),
q('Qual vitamina o corpo consegue produzir na pele com ajuda da luz solar?','Vitamina D',['Vitamina C','Vitamina B12','Vitamina K apenas'],'A luz solar participa da produção de vitamina D na pele.','☀️'),
]},
planetas:{nome:'Planetas e espaço',emoji:'🪐',perguntas:[
q('Qual planeta fica mais perto do Sol?','Mercúrio',['Vênus','Terra','Marte'],'Mercúrio é o primeiro planeta do Sistema Solar.','☀️'),
q('Qual é o planeta mais quente?','Vênus',['Mercúrio','Marte','Júpiter'],'O forte efeito estufa torna Vênus o planeta mais quente.','🔥'),
q('Qual planeta é conhecido como Planeta Vermelho?','Marte',['Vênus','Netuno','Saturno'],'Óxidos de ferro dão a Marte aparência avermelhada.','🔴'),
q('Qual é o maior planeta do Sistema Solar?','Júpiter',['Saturno','Terra','Netuno'],'Júpiter é o planeta de maior diâmetro e massa.','🟠'),
q('Qual planeta é famoso por seus anéis visíveis?','Saturno',['Marte','Mercúrio','Vênus'],'Saturno possui um amplo sistema de anéis.','🪐'),
q('Qual planeta gira quase deitado?','Urano',['Terra','Marte','Mercúrio'],'O eixo de Urano é inclinado em cerca de 98 graus.','🔵'),
q('Qual é o planeta mais distante do Sol entre os oito?','Netuno',['Urano','Saturno','Júpiter'],'Netuno ocupa a oitava órbita planetária.','🌊'),
q('Em qual planeta vivemos?','Terra',['Marte','Vênus','Júpiter'],'A Terra é nosso planeta.','🌍'),
q('Quantos planetas há no Sistema Solar?','Oito',['Sete','Nove','Doze'],'A classificação atual reconhece oito planetas.','🪐'),
q('Plutão é classificado atualmente como quê?','Planeta anão',['Estrela','Lua da Terra','Cometa'],'Plutão é classificado como planeta anão.','🔭'),
q('Qual é o satélite natural da Terra?','Lua',['Sol','Marte','Vênus'],'A Lua orbita a Terra.','🌙'),
q('O Sol é classificado como quê?','Estrela',['Planeta','Satélite','Asteroide'],'O Sol é uma estrela.','☀️'),
q('Como se chama o caminho de um planeta ao redor do Sol?','Órbita',['Eclipse','Cratera','Atmosfera'],'Órbita é a trajetória de um corpo ao redor de outro.','🔄'),
q('Quanto tempo a Terra leva aproximadamente para dar uma volta no Sol?','Um ano',['Um dia','Um mês','Uma semana'],'A translação terrestre dura cerca de 365 dias.','📅'),
q('Quanto tempo a Terra leva aproximadamente para girar sobre seu eixo?','Um dia',['Um ano','Um mês','Uma hora'],'A rotação terrestre dura aproximadamente 24 horas.','🌍'),
q('O que causa dia e noite na Terra?','A rotação da Terra',['As fases da Lua','A chuva','Os anéis de Saturno'],'A rotação alterna as regiões iluminadas pelo Sol.','🌗'),
q('Qual planeta tem a Grande Mancha Vermelha?','Júpiter',['Marte','Vênus','Mercúrio'],'A Grande Mancha Vermelha é uma enorme tempestade em Júpiter.','🌀'),
q('Qual planeta tem uma superfície coberta em grande parte por água líquida?','Terra',['Marte','Mercúrio','Vênus'],'Oceanos cobrem a maior parte da superfície terrestre.','🌊'),
q('Qual planeta tem o dia mais longo que o próprio ano?','Vênus',['Terra','Marte','Júpiter'],'Vênus gira tão lentamente que sua rotação leva mais tempo que sua órbita.','⏳'),
q('Qual destes é um gigante gasoso?','Júpiter',['Terra','Marte','Mercúrio'],'Júpiter é composto principalmente por hidrogênio e hélio.','🟠'),
q('Qual destes é um planeta rochoso?','Marte',['Júpiter','Saturno','Netuno'],'Marte tem superfície sólida e rochosa.','🪨'),
q('Como se chama uma rocha espacial que chega ao solo?','Meteorito',['Meteoroide apenas no espaço','Estrela cadente','Planeta anão'],'Quando um fragmento alcança o solo, recebe o nome de meteorito.','☄️'),
q('O que é uma galáxia?','Um enorme conjunto de estrelas, gás e poeira',['Um único planeta','Uma fase da Lua','Um tipo de foguete'],'Galáxias reúnem muitas estrelas e matéria interestelar.','🌌'),
q('Em qual galáxia fica o Sistema Solar?','Via Láctea',['Andrômeda','Grande Nuvem de Magalhães','Galáxia do Triângulo'],'O Sistema Solar está na Via Láctea.','🌌'),
q('Qual instrumento ajuda a observar astros distantes?','Telescópio',['Microscópio','Termômetro','Estetoscópio'],'Telescópios coletam luz de objetos distantes.','🔭'),
]}});
