import { montarCabecalho } from '../../shared/cabecalho.js';
import { animar, lancarConfete } from '../../shared/confete.js';
import { calcularEstrelas, nomeDaCrianca, obterConfiguracoes, registrarPartida } from '../../shared/progresso.js';
import { tocar } from '../../shared/sons.js';
import { gerarOpcoes, gerarQuestao, idDaTabuada, TABUADAS, TODAS } from './jogo.js';

montarCabecalho('Tabuada Relâmpago');
const $ = id => document.getElementById(id);
const CHAVE_ERROS = 'jogos-elis:tabuada-erros';
const CHAVE_RECORDES = 'jogos-elis:tabuada-recordes';
const ler = chave => { try { return JSON.parse(localStorage.getItem(chave) || '{}'); } catch { return {}; } };
const salvar = (chave, valor) => { try { localStorage.setItem(chave, JSON.stringify(valor)); } catch { /* sem persistência */ } };
let tabuada = 6, ritmo = 'treino', questao, ultimaChave = '', indice = 0, acertos = 0, erros = 0, respondida = false, fimEm = 0, intervalo = null;

function exibir(id){ ['inicio','partida','final'].forEach(t => $(t).hidden = t !== id); }
function selecionarTabuada(valor){ tabuada = valor; document.querySelectorAll('[data-tabuada]').forEach(b => b.setAttribute('aria-pressed', String(b.dataset.tabuada === String(valor)))); atualizarRecorde(); }
function atualizarRecorde(){ const valor = ler(CHAVE_RECORDES)[idDaTabuada(tabuada)] || 0; $('recorde').textContent = `Recorde no Relâmpago: ${valor} acerto${valor === 1 ? '' : 's'}`; }
function montarTabuadas(){ for(const valor of [...TABUADAS, TODAS]){ const b=document.createElement('button'); b.className='botao botao--neutro escolha'; b.dataset.tabuada=valor; b.textContent=valor===TODAS?'Todas':valor; b.addEventListener('click',()=>selecionarTabuada(valor)); $('tabuadas').append(b); } const salva=obterConfiguracoes().niveis.tabuada;selecionarTabuada(salva===TODAS?TODAS:(TABUADAS.includes(Number(salva))?Number(salva):6)); }
function desenharPontos(q){ if(ritmo !== 'treino'){ $('apoio').textContent=''; return; } const pontos=document.createElement('div'); pontos.className='pontos'; pontos.style.gridTemplateColumns=`repeat(${q.colunas}, 1fr)`; pontos.setAttribute('aria-label',`${q.linhas} grupos de ${q.colunas} pontos`); for(let i=0;i<q.linhas*q.colunas;i++){ const p=document.createElement('span'); p.className='ponto'; p.textContent='●'; p.setAttribute('aria-hidden','true'); pontos.append(p); } $('apoio').replaceChildren(pontos); }
function novaQuestao(){ const operacao=$('divisao').checked && Math.random()<.35?'divisao':'multiplicacao'; questao=gerarQuestao(tabuada,operacao,{ultimaChave,errosPorFato:ler(CHAVE_ERROS)}); ultimaChave=questao.chave; respondida=false; $('atual').textContent=indice+1; $('progresso').value=indice; $('conta').textContent=`${questao.numero1} ${questao.simbolo} ${questao.numero2} = ?`; $('feedback').textContent=''; $('feedback').className='feedback'; $('proxima').hidden=true; desenharPontos(questao); $('opcoes').replaceChildren(); $('resposta').value=''; if(ritmo==='treino'){ $('resposta').hidden=true; $('conferir').hidden=true; for(const valor of gerarOpcoes(questao.resposta)){ const b=document.createElement('button'); b.className='botao botao--neutro opcao'; b.textContent=valor; b.addEventListener('click',()=>responder(valor)); $('opcoes').append(b); } } else { $('resposta').hidden=false; $('conferir').hidden=false; $('resposta').disabled=false; $('resposta').focus(); } }
function responder(valor){ if(respondida) return; if(valor === undefined && $('resposta').value==='') return; respondida=true; const certo=Number(valor ?? $('resposta').value)===questao.resposta; if(certo){ acertos++; $('acertos').textContent=acertos; $('feedback').textContent='🎉 Muito bem!'; $('feedback').className='feedback feedback--certo'; tocar('acerto'); animar($('conta'),'pular'); } else { erros++; $('erros').textContent=erros; $('feedback').textContent=`A resposta é ${questao.resposta}.`; $('feedback').className='feedback feedback--errado'; const mapa=ler(CHAVE_ERROS); mapa[questao.chave]=(mapa[questao.chave]||0)+1; salvar(CHAVE_ERROS,mapa); tocar('erro'); animar($('conta'),'tremer'); } $('opcoes').querySelectorAll('button').forEach(b=>b.disabled=true); $('resposta').disabled=true; $('conferir').hidden=true; if(ritmo==='treino'){ $('proxima').hidden=false; $('proxima').textContent=indice===9?'VER RESULTADO':'PRÓXIMA'; $('proxima').focus(); } else setTimeout(()=>{ if(!$('partida').hidden) novaQuestao(); },450); }
function avancar(){ if(!respondida)return; indice++; indice>=10?finalizar():novaQuestao(); }
function iniciar(novoRitmo=ritmo){ ritmo=novoRitmo; indice=0;acertos=0;erros=0;ultimaChave='';$('acertos').textContent='0';$('erros').textContent='0';$('contador').hidden=ritmo==='relampago';$('tempo').hidden=ritmo!=='relampago';$('progresso').hidden=ritmo==='relampago';clearInterval(intervalo);if(ritmo==='relampago'){fimEm=Date.now()+60000;atualizarTempo();intervalo=setInterval(atualizarTempo,250)}exibir('partida');novaQuestao();tocar('clique');}
function atualizarTempo(){ const restante=Math.max(0,Math.ceil((fimEm-Date.now())/1000));$('tempo').textContent=`⏱️ ${restante} s`;if(restante===0)finalizar(); }
function finalizar(){ clearInterval(intervalo);intervalo=null;const estrelas=calcularEstrelas(acertos,erros);registrarPartida('tabuada',{acertos,erros,estrelas});$('resumo').textContent=`${nomeDaCrianca()}, você acertou ${acertos} e errou ${erros}.`;$('estrelas').textContent='⭐'.repeat(estrelas);$('novo-recorde').textContent='';if(ritmo==='relampago'){const recordes=ler(CHAVE_RECORDES),id=idDaTabuada(tabuada),anterior=recordes[id]||0;if(acertos>anterior){recordes[id]=acertos;salvar(CHAVE_RECORDES,recordes);$('novo-recorde').textContent='⚡ Novo recorde!';}}exibir('final');tocar('vitoria');lancarConfete();}

document.querySelectorAll('.modo').forEach(b=>b.addEventListener('click',()=>iniciar(b.dataset.ritmo)));$('conferir').addEventListener('click',()=>responder());$('proxima').addEventListener('click',avancar);$('sair').addEventListener('click',()=>{clearInterval(intervalo);exibir('inicio');atualizarRecorde()});$('de-novo').addEventListener('click',()=>iniciar());$('trocar').addEventListener('click',()=>{exibir('inicio');atualizarRecorde()});$('resposta').addEventListener('keydown',e=>{if(e.key==='Enter')responder()});montarTabuadas();
