import { montarCabecalho } from '../../shared/cabecalho.js';import { animar,lancarConfete } from '../../shared/confete.js';import { calcularEstrelas,nomeDaCrianca,obterConfiguracoes,registrarPartida } from '../../shared/progresso.js';import { tocar } from '../../shared/sons.js';import { conferirDados,conferirPagamento,denominacoesDoNivel,formatarDinheiro,montarRodada,somarCentavos,valorDaQuestao } from './jogo.js';
montarCabecalho('Dinheirinho');const problemas=conferirDados();if(problemas.length)throw new Error(problemas.join('\n'));const $=id=>document.getElementById(id);let nivel=Number(obterConfiguracoes().niveis.dinheirinho)||2,rodada=[],indice=0,item,valores=[],acertos=0,erros=0,respondida=false;
function exibir(id){['inicio','partida','final'].forEach(t=>$(t).hidden=t!==id)}function selecionar(n){nivel=Number(n);document.querySelectorAll('[data-nivel]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.nivel)===nivel)))}document.querySelectorAll('[data-nivel]').forEach(b=>b.addEventListener('click',()=>selecionar(b.dataset.nivel)));selecionar([1,2,3].includes(nivel)?nivel:2);
function desenharDinheiro(){const caixa=$('dinheiro');caixa.replaceChildren();for(const valor of denominacoesDoNivel(nivel)){const b=document.createElement('button');b.className=`valor ${valor<200?'moeda':'nota'}`;b.textContent=formatarDinheiro(valor).replace('R$ ','');b.setAttribute('aria-label',`Adicionar ${formatarDinheiro(valor)}`);b.addEventListener('click',()=>adicionar(valor));caixa.append(b)}}function atualizar(){const total=somarCentavos(valores);$('total').textContent=formatarDinheiro(total);$('usado').textContent=valores.length?valores.map(formatarDinheiro).join(' + '):'Toque no dinheiro para começar.'}
function mostrar(){item=rodada[indice];valores=[];respondida=false;$('atual').textContent=indice+1;$('progresso').value=indice;$('produto').textContent=item.emoji;$('nome').textContent=item.nome;$('preco').textContent=`Preço: ${formatarDinheiro(item.preco)}`;$('pedido').textContent=nivel===3?`O cliente pagou ${formatarDinheiro(item.pago)}. Quanto recebe de troco?`:'Monte o preço exato.';$('feedback').textContent='';$('feedback').className='feedback';$('conferir').hidden=false;$('proxima').hidden=true;desenharDinheiro();atualizar()}
function adicionar(valor){if(respondida)return;valores.push(valor);atualizar();tocar('clique')}function desfazer(){if(respondida)return;valores.pop();atualizar();tocar('clique')}
function conferir(){if(respondida)return;if(!valores.length){$('feedback').textContent='Escolha pelo menos uma moeda ou nota.';return}respondida=true;const certo=conferirPagamento(valores,item);if(certo){acertos++;$('acertos').textContent=acertos;$('feedback').textContent='🎉 Valor certinho!';$('feedback').className='feedback feedback--certo';tocar('acerto');animar($('total'),'pular')}else{erros++;$('erros').textContent=erros;$('feedback').textContent=`O valor certo era ${formatarDinheiro(valorDaQuestao(item))}.`;$('feedback').className='feedback feedback--errado';tocar('erro');animar($('total'),'tremer')}$('dinheiro').querySelectorAll('button').forEach(b=>b.disabled=true);$('conferir').hidden=true;$('proxima').hidden=false;$('proxima').textContent=indice===9?'VER RESULTADO':'PRÓXIMA'}
function iniciar(){rodada=montarRodada(nivel);indice=0;acertos=0;erros=0;$('acertos').textContent='0';$('erros').textContent='0';exibir('partida');mostrar();tocar('clique')}function avancar(){if(!respondida)return;indice++;if(indice>=10){const estrelas=calcularEstrelas(acertos,erros);registrarPartida('dinheirinho',{acertos,erros,estrelas});$('resumo').textContent=`${nomeDaCrianca()}, você acertou ${acertos} de 10 valores.`;$('estrelas').textContent='⭐'.repeat(estrelas);exibir('final');tocar('vitoria');lancarConfete()}else mostrar()}
$('comecar').addEventListener('click',iniciar);$('desfazer').addEventListener('click',desfazer);$('conferir').addEventListener('click',conferir);$('proxima').addEventListener('click',avancar);$('sair').addEventListener('click',()=>exibir('inicio'));$('de-novo').addEventListener('click',iniciar);$('trocar').addEventListener('click',()=>exibir('inicio'));
