/**
 * dados.js — os pacotes de regras da Ortografia Divertida (J01).
 *
 * Cada pacote tem a regra em uma frase, as opções que aparecem nos botões e a
 * lista de itens. Um item é sempre `{ texto, resposta, palavra, dica }`:
 *
 *   texto    a palavra com UMA lacuna, marcada por "_"
 *   resposta o que preenche a lacuna (pode ter mais de uma letra: RR, SS, CH)
 *   palavra  o resultado de trocar o "_" pela resposta — conferido no teste
 *   dica     uma frase que identifica a palavra
 *
 * Por que a dica existe: em vários casos a lacuna sozinha não decide a
 * resposta ("CA_O" pode virar CARO ou CARRO). A dica diz de qual palavra se
 * trata, e aí só uma das opções está certa. O pacote "m-n" é a exceção: ali a
 * letra seguinte já decide (antes de P e B é sempre M), então não tem dica.
 *
 * Palavras escolhidas evitando pares em que as duas opções dariam palavras
 * reais (ALTO/AUTO, MEU/MEL, MAU/MAL, ASA/ASSA, ROSA/ROÇA ficaram de fora).
 * Grafia e acentuação conferidas item a item.
 */
import { gerarLacuna, listaDePalavras } from '../m-ou-n/jogo.js';

/* O pacote 1 reaproveita a lista da T04: a lacuna sai da mesma função que o
   jogo do M ou N usa, então as duas telas nunca discordam. */
const itensMN = listaDePalavras.map(palavra => {
  const { texto, resposta } = gerarLacuna(palavra);
  return { texto, resposta, palavra };
});

export const pacotes = {
  'm-n': {
    id: 'm-n',
    nome: 'M ou N',
    emoji: '✏️',
    nivel: 1,
    regra: 'Antes de P e B usamos M. Antes das outras letras usamos N.',
    exemplo: 'CA_PO → CAMPO',
    opcoes: ['M', 'N'],
    itens: itensMN,
  },

  'r-rr': {
    id: 'r-rr',
    nome: 'R ou RR',
    emoji: '🚗',
    nivel: 2,
    regra: 'Entre duas vogais, o som forte do R se escreve RR. O R sozinho entre vogais tem som fraco.',
    exemplo: 'CA_O → CARRO',
    opcoes: ['R', 'RR'],
    itens: [
      { texto: 'CA_O', resposta: 'RR', palavra: 'CARRO', dica: 'Tem quatro rodas, volante e leva a família para passear.' },
      { texto: 'CACHO_O', resposta: 'RR', palavra: 'CACHORRO', dica: 'Late e abana o rabo quando você chega em casa.' },
      { texto: 'BA_IGA', resposta: 'RR', palavra: 'BARRIGA', dica: 'Ronca quando estamos com fome.' },
      { texto: 'TE_A', resposta: 'RR', palavra: 'TERRA', dica: 'O planeta onde a gente mora.' },
      { texto: 'FE_O', resposta: 'RR', palavra: 'FERRO', dica: 'Metal pesado; também é o aparelho que alisa a roupa.' },
      { texto: 'GUE_A', resposta: 'RR', palavra: 'GUERRA', dica: 'Briga entre países.' },
      { texto: 'SOCO_O', resposta: 'RR', palavra: 'SOCORRO', dica: 'O grito de quem precisa de ajuda depressa.' },
      { texto: 'BU_O', resposta: 'RR', palavra: 'BURRO', dica: 'Parente do cavalo, de orelhas bem grandes.' },
      { texto: 'JA_A', resposta: 'RR', palavra: 'JARRA', dica: 'Fica na mesa cheia de suco.' },
      { texto: 'BA_O', resposta: 'RR', palavra: 'BARRO', dica: 'Terra molhada que vira vaso e tijolo.' },
      { texto: 'CO_IDA', resposta: 'RR', palavra: 'CORRIDA', dica: 'Prova em que ganha quem chega primeiro.' },
      { texto: 'TO_E', resposta: 'RR', palavra: 'TORRE', dica: 'Construção bem alta e estreita.' },
      { texto: 'BEZE_O', resposta: 'RR', palavra: 'BEZERRO', dica: 'O filhote da vaca.' },
      { texto: 'A_OZ', resposta: 'RR', palavra: 'ARROZ', dica: 'Companheiro do feijão no prato.' },
      { texto: 'FE_AMENTA', resposta: 'RR', palavra: 'FERRAMENTA', dica: 'O martelo e a chave de fenda são exemplos.' },
      { texto: 'GA_AFA', resposta: 'RR', palavra: 'GARRAFA', dica: 'Guarda a água e tem tampinha.' },
      { texto: 'GO_O', resposta: 'RR', palavra: 'GORRO', dica: 'Touca de lã que esquenta a cabeça.' },
      { texto: 'SE_OTE', resposta: 'RR', palavra: 'SERROTE', dica: 'Serve para serrar madeira.' },
      { texto: 'TE_ÍVEL', resposta: 'RR', palavra: 'TERRÍVEL', dica: 'Muito ruim, de dar medo.' },
      { texto: 'CO_EIO', resposta: 'RR', palavra: 'CORREIO', dica: 'Leva as cartas e as encomendas.' },
      { texto: 'BO_ACHA', resposta: 'RR', palavra: 'BORRACHA', dica: 'Apaga o que foi escrito a lápis.' },
      { texto: 'CHU_ASCO', resposta: 'RR', palavra: 'CHURRASCO', dica: 'Carne assada na brasa no fim de semana.' },
      { texto: 'GUITA_A', resposta: 'RR', palavra: 'GUITARRA', dica: 'Instrumento de cordas das bandas de rock.' },
      { texto: 'TO_ADA', resposta: 'RR', palavra: 'TORRADA', dica: 'Pão bem tostado do café da manhã.' },
      { texto: 'MACA_ÃO', resposta: 'RR', palavra: 'MACARRÃO', dica: 'Massa italiana que se come com molho.' },
      { texto: 'TARTA_UGA', resposta: 'R', palavra: 'TARTARUGA', dica: 'Anda devagar e carrega a casa nas costas.' },
      { texto: 'CO_UJA', resposta: 'R', palavra: 'CORUJA', dica: 'Ave que fica acordada à noite.' },
      { texto: 'TESOU_A', resposta: 'R', palavra: 'TESOURA', dica: 'Tem duas lâminas e corta papel.' },
      { texto: 'SE_EIA', resposta: 'R', palavra: 'SEREIA', dica: 'Metade mulher, metade peixe.' },
      { texto: 'LA_ANJA', resposta: 'R', palavra: 'LARANJA', dica: 'Fruta do suco do café da manhã.' },
      { texto: 'TOU_O', resposta: 'R', palavra: 'TOURO', dica: 'Boi bravo de chifres.' },
      { texto: 'MADEI_A', resposta: 'R', palavra: 'MADEIRA', dica: 'Vem da árvore e vira mesa e cadeira.' },
      { texto: 'CANGU_U', resposta: 'R', palavra: 'CANGURU', dica: 'Pula e leva o filhote na bolsa.' },
      { texto: 'GI_AFA', resposta: 'R', palavra: 'GIRAFA', dica: 'Tem o pescoço mais comprido do zoológico.' },
      { texto: 'PI_ATA', resposta: 'R', palavra: 'PIRATA', dica: 'Navega procurando tesouro.' },
      { texto: 'FE_IDA', resposta: 'R', palavra: 'FERIDA', dica: 'Machucado na pele que precisa de curativo.' },
      { texto: 'CO_AÇÃO', resposta: 'R', palavra: 'CORAÇÃO', dica: 'Bate dentro do peito.' },
      { texto: 'A_ARA', resposta: 'R', palavra: 'ARARA', dica: 'Ave bem colorida que repete o que ouve.' },
      { texto: 'CENOU_A', resposta: 'R', palavra: 'CENOURA', dica: 'Legume laranja que o coelho adora.' },
      { texto: 'AMA_ELO', resposta: 'R', palavra: 'AMARELO', dica: 'A cor do sol e do pintinho.' },
      { texto: 'PA_AFUSO', resposta: 'R', palavra: 'PARAFUSO', dica: 'Entra na madeira girando.' },
      { texto: 'FA_INHA', resposta: 'R', palavra: 'FARINHA', dica: 'Pó branco que vira bolo e pão.' },
      { texto: 'BA_ATA', resposta: 'R', palavra: 'BARATA', dica: 'Inseto que corre pela cozinha.' },
    ],
  },

  's-ss': {
    id: 's-ss',
    nome: 'S ou SS',
    emoji: '🐦',
    nivel: 2,
    regra: 'Entre duas vogais, o som forte de S se escreve SS. Um S sozinho entre vogais tem som de Z.',
    exemplo: 'PÁ_ARO → PÁSSARO',
    opcoes: ['S', 'SS'],
    itens: [
      { texto: 'PÁ_ARO', resposta: 'SS', palavra: 'PÁSSARO', dica: 'Bicho de penas que canta na janela.' },
      { texto: 'PE_OA', resposta: 'SS', palavra: 'PESSOA', dica: 'Cada gente do mundo é uma.' },
      { texto: 'O_O', resposta: 'SS', palavra: 'OSSO', dica: 'É duro e fica dentro do corpo.' },
      { texto: 'NO_O', resposta: 'SS', palavra: 'NOSSO', dica: 'O que é meu e seu ao mesmo tempo.' },
      { texto: 'MA_A', resposta: 'SS', palavra: 'MASSA', dica: 'Vira pizza depois de ir ao forno.' },
      { texto: 'PROFE_OR', resposta: 'SS', palavra: 'PROFESSOR', dica: 'Quem ensina a turma na escola.' },
      { texto: 'VA_OURA', resposta: 'SS', palavra: 'VASSOURA', dica: 'Varre o chão da casa.' },
      { texto: 'PA_EIO', resposta: 'SS', palavra: 'PASSEIO', dica: 'Um programa gostoso fora de casa.' },
      { texto: 'CLA_E', resposta: 'SS', palavra: 'CLASSE', dica: 'A turma toda da sala de aula.' },
      { texto: 'A_USTAR', resposta: 'SS', palavra: 'ASSUSTAR', dica: 'Dar um susto em alguém.' },
      { texto: 'PÊ_EGO', resposta: 'SS', palavra: 'PÊSSEGO', dica: 'Fruta amarelada de casquinha aveludada.' },
      { texto: 'TRAVE_EIRO', resposta: 'SS', palavra: 'TRAVESSEIRO', dica: 'Onde a cabeça descansa na cama.' },
      { texto: 'INTERE_ANTE', resposta: 'SS', palavra: 'INTERESSANTE', dica: 'Que desperta curiosidade.' },
      { texto: 'NECE_ÁRIO', resposta: 'SS', palavra: 'NECESSÁRIO', dica: 'Aquilo que a gente precisa mesmo.' },
      { texto: 'A_UNTO', resposta: 'SS', palavra: 'ASSUNTO', dica: 'O tema de uma conversa.' },
      { texto: 'MA_AGEM', resposta: 'SS', palavra: 'MASSAGEM', dica: 'Aperta as costas para relaxar.' },
      { texto: 'GRO_O', resposta: 'SS', palavra: 'GROSSO', dica: 'O contrário de fino.' },
      { texto: 'A_ADO', resposta: 'SS', palavra: 'ASSADO', dica: 'Frango que foi ao forno.' },
      { texto: 'BÚ_OLA', resposta: 'SS', palavra: 'BÚSSOLA', dica: 'A agulha dela aponta para o norte.' },
      { texto: 'MI_ÃO', resposta: 'SS', palavra: 'MISSÃO', dica: 'Uma tarefa importante para cumprir.' },
      { texto: 'TRAVE_A', resposta: 'SS', palavra: 'TRAVESSA', dica: 'Prato grande de servir comida.' },
      { texto: 'PA_O', resposta: 'SS', palavra: 'PASSO', dica: 'Cada vez que o pé vai para a frente.' },
      { texto: 'A_IM', resposta: 'SS', palavra: 'ASSIM', dica: 'Deste jeito.' },
      { texto: 'CARRO_EL', resposta: 'SS', palavra: 'CARROSSEL', dica: 'Brinquedo do parque que gira com cavalinhos.' },
      { texto: 'COI_A', resposta: 'S', palavra: 'COISA', dica: 'Um objeto qualquer.' },
      { texto: 'ME_A', resposta: 'S', palavra: 'MESA', dica: 'Tem quatro pés e a gente almoça nela.' },
      { texto: 'CAMI_A', resposta: 'S', palavra: 'CAMISA', dica: 'Roupa de botões que cobre o tronco.' },
      { texto: 'TE_OURO', resposta: 'S', palavra: 'TESOURO', dica: 'Baú cheio de moedas de ouro.' },
      { texto: 'BLU_A', resposta: 'S', palavra: 'BLUSA', dica: 'Roupa que se veste por cima.' },
      { texto: 'SURPRE_A', resposta: 'S', palavra: 'SURPRESA', dica: 'O que ninguém esperava na festa.' },
      { texto: 'DEFE_A', resposta: 'S', palavra: 'DEFESA', dica: 'A parte do time que protege o gol.' },
      { texto: 'PE_ADO', resposta: 'S', palavra: 'PESADO', dica: 'O contrário de leve.' },
      { texto: 'CA_ACO', resposta: 'S', palavra: 'CASACO', dica: 'Roupa de frio com mangas compridas.' },
      { texto: 'MU_EU', resposta: 'S', palavra: 'MUSEU', dica: 'Lugar que guarda quadros e dinossauros.' },
      { texto: 'VA_O', resposta: 'S', palavra: 'VASO', dica: 'A planta mora dentro dele.' },
      { texto: 'GA_OLINA', resposta: 'S', palavra: 'GASOLINA', dica: 'O carro bebe no posto.' },
      { texto: 'PESQUI_A', resposta: 'S', palavra: 'PESQUISA', dica: 'Procurar informação para aprender.' },
      { texto: 'SOBREME_A', resposta: 'S', palavra: 'SOBREMESA', dica: 'O doce do fim do almoço.' },
      { texto: 'FRA_E', resposta: 'S', palavra: 'FRASE', dica: 'Um conjunto de palavras com sentido.' },
      { texto: 'BRA_IL', resposta: 'S', palavra: 'BRASIL', dica: 'O nome do nosso país.' },
      { texto: 'RI_ADA', resposta: 'S', palavra: 'RISADA', dica: 'O barulho de quem acha graça.' },
    ],
  },

  'g-j': {
    id: 'g-j',
    nome: 'G ou J',
    emoji: '🕐',
    nivel: 3,
    regra: 'As terminações -AGEM, -ÁGIO e -ÉGIO se escrevem com G. As palavras da família de outra com JA, JO ou JU guardam o J (LOJA → LOJINHA).',
    exemplo: 'VIA_EM → VIAGEM',
    opcoes: ['G', 'J'],
    itens: [
      { texto: 'VIA_EM', resposta: 'G', palavra: 'VIAGEM', dica: 'Ir passar uns dias longe de casa.' },
      { texto: 'CORA_EM', resposta: 'G', palavra: 'CORAGEM', dica: 'O contrário de medo.' },
      { texto: 'GARA_EM', resposta: 'G', palavra: 'GARAGEM', dica: 'Onde o carro dorme.' },
      { texto: 'PAISA_EM', resposta: 'G', palavra: 'PAISAGEM', dica: 'A vista bonita da janela.' },
      { texto: 'MENSA_EM', resposta: 'G', palavra: 'MENSAGEM', dica: 'O que a gente manda pelo celular.' },
      { texto: 'RELÓ_IO', resposta: 'G', palavra: 'RELÓGIO', dica: 'Mostra as horas no pulso.' },
      { texto: 'COLÉ_IO', resposta: 'G', palavra: 'COLÉGIO', dica: 'Outro nome para escola.' },
      { texto: '_IRAFA', resposta: 'G', palavra: 'GIRAFA', dica: 'Bicho alto de pescoço comprido.' },
      { texto: '_ELO', resposta: 'G', palavra: 'GELO', dica: 'Água dura que vem do congelador.' },
      { texto: '_ENTE', resposta: 'G', palavra: 'GENTE', dica: 'Um monte de pessoas.' },
      { texto: '_IGANTE', resposta: 'G', palavra: 'GIGANTE', dica: 'Enorme, do tamanho de um prédio.' },
      { texto: 'MÁ_ICO', resposta: 'G', palavra: 'MÁGICO', dica: 'Tira o coelho da cartola.' },
      { texto: 'TI_ELA', resposta: 'G', palavra: 'TIGELA', dica: 'Vasilha funda do cereal com leite.' },
      { texto: '_EMA', resposta: 'G', palavra: 'GEMA', dica: 'A parte amarela do ovo.' },
      { texto: 'FERRU_EM', resposta: 'G', palavra: 'FERRUGEM', dica: 'Mancha laranja no ferro que ficou na chuva.' },
      { texto: '_ELADEIRA', resposta: 'G', palavra: 'GELADEIRA', dica: 'Guarda a comida no frio.' },
      { texto: '_IRASSOL', resposta: 'G', palavra: 'GIRASSOL', dica: 'Flor amarela que acompanha o sol.' },
      { texto: 'ORI_EM', resposta: 'G', palavra: 'ORIGEM', dica: 'O lugar de onde uma coisa veio.' },
      { texto: 'VA_EM', resposta: 'G', palavra: 'VAGEM', dica: 'Legume verde e comprido.' },
      { texto: 'BAGA_EM', resposta: 'G', palavra: 'BAGAGEM', dica: 'As malas de quem vai viajar.' },
      { texto: '_ELATINA', resposta: 'G', palavra: 'GELATINA', dica: 'Doce colorido que treme no prato.' },
      { texto: 'PERSONA_EM', resposta: 'G', palavra: 'PERSONAGEM', dica: 'Quem aparece na história do livro.' },
      { texto: 'A_ENDA', resposta: 'G', palavra: 'AGENDA', dica: 'Caderninho de anotar os compromissos.' },
      { texto: 'ESTRAN_EIRO', resposta: 'G', palavra: 'ESTRANGEIRO', dica: 'Quem vem de outro país.' },
      { texto: '_INÁSTICA', resposta: 'G', palavra: 'GINÁSTICA', dica: 'Esporte de saltos e piruetas.' },
      { texto: 'HO_E', resposta: 'J', palavra: 'HOJE', dica: 'O dia de agora.' },
      { texto: 'LO_A', resposta: 'J', palavra: 'LOJA', dica: 'Lugar onde a gente compra as coisas.' },
      { texto: '_ILÓ', resposta: 'J', palavra: 'JILÓ', dica: 'Legume verde e amarguinho.' },
      { texto: 'CAN_ICA', resposta: 'J', palavra: 'CANJICA', dica: 'Doce de milho da festa junina.' },
      { texto: 'LARAN_EIRA', resposta: 'J', palavra: 'LARANJEIRA', dica: 'A árvore que dá laranja.' },
      { texto: '_EITO', resposta: 'J', palavra: 'JEITO', dica: 'O modo de fazer alguma coisa.' },
      { texto: 'GOR_ETA', resposta: 'J', palavra: 'GORJETA', dica: 'O dinheirinho a mais deixado no restaurante.' },
      { texto: '_IBOIA', resposta: 'J', palavra: 'JIBOIA', dica: 'Cobra grande que aperta a presa.' },
      { texto: 'SU_EIRA', resposta: 'J', palavra: 'SUJEIRA', dica: 'O que a vassoura tira do chão.' },
      { texto: 'CERE_A', resposta: 'J', palavra: 'CEREJA', dica: 'Frutinha vermelha que enfeita o bolo.' },
      { texto: 'IGRE_A', resposta: 'J', palavra: 'IGREJA', dica: 'Prédio com torre e sino onde se reza.' },
      { texto: '_ENIPAPO', resposta: 'J', palavra: 'JENIPAPO', dica: 'Fruta do Norte que dá tinta escura.' },
      { texto: 'PRO_ETO', resposta: 'J', palavra: 'PROJETO', dica: 'O plano de uma coisa que vamos fazer.' },
      { texto: '_EGUE', resposta: 'J', palavra: 'JEGUE', dica: 'O jumento do sertão.' },
      { texto: 'BERIN_ELA', resposta: 'J', palavra: 'BERINJELA', dica: 'Legume roxo e comprido.' },
      { texto: 'NO_ENTO', resposta: 'J', palavra: 'NOJENTO', dica: 'Que dá nojo.' },
    ],
  },

  'x-ch': {
    id: 'x-ch',
    nome: 'X ou CH',
    emoji: '🍫',
    nivel: 3,
    regra: 'Depois das sílabas ME e EN quase sempre escrevemos X (MEXER, ENXADA). Nas outras palavras o som costuma ser CH.',
    exemplo: 'ME_ER → MEXER',
    opcoes: ['X', 'CH'],
    itens: [
      { texto: 'ME_ER', resposta: 'X', palavra: 'MEXER', dica: 'Girar a colher dentro do suco.' },
      { texto: 'EN_ADA', resposta: 'X', palavra: 'ENXADA', dica: 'Ferramenta de cabo comprido para capinar.' },
      { texto: 'EN_AME', resposta: 'X', palavra: 'ENXAME', dica: 'Um monte de abelhas voando juntas.' },
      { texto: 'EN_UGAR', resposta: 'X', palavra: 'ENXUGAR', dica: 'Secar com a toalha.' },
      { texto: 'EN_OVAL', resposta: 'X', palavra: 'ENXOVAL', dica: 'As roupinhas preparadas para o bebê.' },
      { texto: 'ME_ERICA', resposta: 'X', palavra: 'MEXERICA', dica: 'Parecida com a laranja e fácil de descascar.' },
      { texto: 'EN_ERGAR', resposta: 'X', palavra: 'ENXERGAR', dica: 'Conseguir ver.' },
      { texto: 'EN_AQUECA', resposta: 'X', palavra: 'ENXAQUECA', dica: 'Dor de cabeça bem forte.' },
      { texto: 'ME_ICANO', resposta: 'X', palavra: 'MEXICANO', dica: 'Quem nasceu no México.' },
      { texto: 'EN_OFRE', resposta: 'X', palavra: 'ENXOFRE', dica: 'Pó amarelo de cheiro ruim.' },
      { texto: '_ÍCARA', resposta: 'X', palavra: 'XÍCARA', dica: 'Copinho com asa para o café.' },
      { texto: '_AROPE', resposta: 'X', palavra: 'XAROPE', dica: 'Remédio doce para a tosse.' },
      { texto: 'LI_O', resposta: 'X', palavra: 'LIXO', dica: 'Vai para a lixeira.' },
      { texto: 'CAI_A', resposta: 'X', palavra: 'CAIXA', dica: 'De papelão, guarda coisas dentro.' },
      { texto: 'PEI_E', resposta: 'X', palavra: 'PEIXE', dica: 'Nada no rio e tem escamas.' },
      { texto: 'BRU_A', resposta: 'X', palavra: 'BRUXA', dica: 'Voa na vassoura e ri alto.' },
      { texto: 'FAI_A', resposta: 'X', palavra: 'FAIXA', dica: 'Tira comprida de pano.' },
      { texto: 'ABACA_I', resposta: 'X', palavra: 'ABACAXI', dica: 'Fruta espinhenta com uma coroa em cima.' },
      { texto: '_ADREZ', resposta: 'X', palavra: 'XADREZ', dica: 'Jogo de tabuleiro do rei e da rainha.' },
      { texto: '_AMPU', resposta: 'X', palavra: 'XAMPU', dica: 'Lava o cabelo no banho.' },
      { texto: 'RO_O', resposta: 'X', palavra: 'ROXO', dica: 'A cor da uva.' },
      { texto: 'BAI_O', resposta: 'X', palavra: 'BAIXO', dica: 'O contrário de alto.' },
      { texto: 'LAGARTI_A', resposta: 'X', palavra: 'LAGARTIXA', dica: 'Lagarto pequeno que sobe na parede.' },
      { texto: 'QUEI_O', resposta: 'X', palavra: 'QUEIXO', dica: 'Fica logo abaixo da boca.' },
      { texto: '_UVA', resposta: 'CH', palavra: 'CHUVA', dica: 'Cai do céu e molha tudo.' },
      { texto: '_OCOLATE', resposta: 'CH', palavra: 'CHOCOLATE', dica: 'Doce marrom da Páscoa.' },
      { texto: '_INELO', resposta: 'CH', palavra: 'CHINELO', dica: 'Calçado de dedo para andar em casa.' },
      { texto: '_AVE', resposta: 'CH', palavra: 'CHAVE', dica: 'Abre a fechadura da porta.' },
      { texto: 'CA_ECOL', resposta: 'CH', palavra: 'CACHECOL', dica: 'Enrola no pescoço quando faz frio.' },
      { texto: 'MO_ILA', resposta: 'CH', palavra: 'MOCHILA', dica: 'Leva o material nas costas até a escola.' },
      { texto: 'FE_ADURA', resposta: 'CH', palavra: 'FECHADURA', dica: 'A parte da porta onde a chave entra.' },
      { texto: '_IMPANZÉ', resposta: 'CH', palavra: 'CHIMPANZÉ', dica: 'Macaco bem espertinho.' },
      { texto: 'BI_O', resposta: 'CH', palavra: 'BICHO', dica: 'Outro jeito de dizer animal.' },
      { texto: 'FLE_A', resposta: 'CH', palavra: 'FLECHA', dica: 'O arco atira ela longe.' },
      { texto: 'CO_ILO', resposta: 'CH', palavra: 'COCHILO', dica: 'Uma soneca rapidinha.' },
      { texto: 'MA_UCADO', resposta: 'CH', palavra: 'MACHUCADO', dica: 'O joelho fica assim depois do tombo.' },
      { texto: 'RA_ADURA', resposta: 'CH', palavra: 'RACHADURA', dica: 'Fenda que aparece na parede.' },
      { texto: '_IFRE', resposta: 'CH', palavra: 'CHIFRE', dica: 'O boi tem dois na cabeça.' },
      { texto: 'FANTO_E', resposta: 'CH', palavra: 'FANTOCHE', dica: 'Boneco que se mexe com a mão dentro.' },
      { texto: '_UCHU', resposta: 'CH', palavra: 'CHUCHU', dica: 'Legume verde claro que se come cozido.' },
      { texto: 'CA_OEIRA', resposta: 'CH', palavra: 'CACHOEIRA', dica: 'Água do rio caindo lá do alto.' },
    ],
  },

  'c-ss-s': {
    id: 'c-ss-s',
    nome: 'Ç, SS ou S',
    emoji: '🍎',
    nivel: 4,
    regra: 'O Ç e o SS têm o mesmo som forte: depois de consoante só cabe o Ç (DANÇA); entre vogais pode ser Ç ou SS, e o S sozinho entre vogais tem som de Z.',
    exemplo: 'CRIAN_A → CRIANÇA',
    opcoes: ['Ç', 'SS', 'S'],
    itens: [
      { texto: 'CRIAN_A', resposta: 'Ç', palavra: 'CRIANÇA', dica: 'Gente pequena que adora brincar.' },
      { texto: 'DAN_A', resposta: 'Ç', palavra: 'DANÇA', dica: 'Mexer o corpo no ritmo da música.' },
      { texto: 'CAN_ÃO', resposta: 'Ç', palavra: 'CANÇÃO', dica: 'Outro nome para música cantada.' },
      { texto: 'ESPERAN_A', resposta: 'Ç', palavra: 'ESPERANÇA', dica: 'A certeza de que vai dar certo.' },
      { texto: 'LAN_AR', resposta: 'Ç', palavra: 'LANÇAR', dica: 'Jogar a bola bem longe.' },
      { texto: 'FOR_A', resposta: 'Ç', palavra: 'FORÇA', dica: 'O que o super-herói tem de sobra.' },
      { texto: 'BER_O', resposta: 'Ç', palavra: 'BERÇO', dica: 'A caminha do bebê.' },
      { texto: 'CAL_A', resposta: 'Ç', palavra: 'CALÇA', dica: 'Roupa de duas pernas.' },
      { texto: 'ALMO_O', resposta: 'Ç', palavra: 'ALMOÇO', dica: 'A refeição do meio do dia.' },
      { texto: 'TER_A', resposta: 'Ç', palavra: 'TERÇA', dica: 'O dia da semana depois da segunda.' },
      { texto: 'LOU_A', resposta: 'Ç', palavra: 'LOUÇA', dica: 'O que fica na pia depois do jantar.' },
      { texto: 'BALAN_O', resposta: 'Ç', palavra: 'BALANÇO', dica: 'Vai e vem pendurado no parquinho.' },
      { texto: 'MUDAN_A', resposta: 'Ç', palavra: 'MUDANÇA', dica: 'Levar os móveis para outra casa.' },
      { texto: 'PESCO_O', resposta: 'Ç', palavra: 'PESCOÇO', dica: 'Liga a cabeça ao corpo.' },
      { texto: 'A_ÚCAR', resposta: 'Ç', palavra: 'AÇÚCAR', dica: 'Pó branco que adoça o café.' },
      { texto: 'PO_O', resposta: 'Ç', palavra: 'POÇO', dica: 'Buraco fundo de onde se tira água.' },
      { texto: 'LA_O', resposta: 'Ç', palavra: 'LAÇO', dica: 'Fita amarrada em forma de borboleta.' },
      { texto: 'MO_A', resposta: 'Ç', palavra: 'MOÇA', dica: 'Mulher jovem.' },
      { texto: 'CABE_A', resposta: 'Ç', palavra: 'CABEÇA', dica: 'Onde ficam os olhos e o cérebro.' },
      { texto: 'PREGUI_A', resposta: 'Ç', palavra: 'PREGUIÇA', dica: 'Vontade nenhuma de levantar; também é um bicho lento.' },
      { texto: 'MA_Ã', resposta: 'Ç', palavra: 'MAÇÃ', dica: 'Fruta vermelha da Branca de Neve.' },
      { texto: 'A_AÍ', resposta: 'Ç', palavra: 'AÇAÍ', dica: 'Fruta roxa do Pará que vira sorvete.' },
      { texto: 'LINGUI_A', resposta: 'Ç', palavra: 'LINGUIÇA', dica: 'Carne temperada dentro de uma tripa fininha.' },
      { texto: 'A_OPRAR', resposta: 'SS', palavra: 'ASSOPRAR', dica: 'O que se faz nas velinhas do bolo.' },
      { texto: 'PA_AGEM', resposta: 'SS', palavra: 'PASSAGEM', dica: 'O bilhete do ônibus.' },
      { texto: 'MA_AGEM', resposta: 'SS', palavra: 'MASSAGEM', dica: 'Aperta as costas para relaxar.' },
      { texto: 'PA_ADO', resposta: 'SS', palavra: 'PASSADO', dica: 'O tempo que já foi embora.' },
      { texto: 'AMA_AR', resposta: 'SS', palavra: 'AMASSAR', dica: 'Apertar o papel até virar uma bolinha.' },
      { texto: 'ATRAVE_AR', resposta: 'SS', palavra: 'ATRAVESSAR', dica: 'Passar de um lado da rua para o outro.' },
      { texto: 'A_OBIAR', resposta: 'SS', palavra: 'ASSOBIAR', dica: 'Fazer música só com a boca.' },
      { texto: 'INTERE_ANTE', resposta: 'SS', palavra: 'INTERESSANTE', dica: 'Que desperta curiosidade.' },
      { texto: 'SO_EGO', resposta: 'SS', palavra: 'SOSSEGO', dica: 'Paz e silêncio para descansar.' },
      { texto: 'PA_ARELA', resposta: 'SS', palavra: 'PASSARELA', dica: 'Ponte só para pedestres.' },
      { texto: 'PROFE_ORA', resposta: 'SS', palavra: 'PROFESSORA', dica: 'Quem ensina a turma na escola.' },
      { texto: 'CAMI_A', resposta: 'S', palavra: 'CAMISA', dica: 'Roupa de botões que cobre o tronco.' },
      { texto: 'TE_OURO', resposta: 'S', palavra: 'TESOURO', dica: 'Baú cheio de moedas de ouro.' },
      { texto: 'BLU_A', resposta: 'S', palavra: 'BLUSA', dica: 'Roupa que se veste por cima.' },
      { texto: 'MU_EU', resposta: 'S', palavra: 'MUSEU', dica: 'Lugar que guarda quadros e dinossauros.' },
      { texto: 'GA_OLINA', resposta: 'S', palavra: 'GASOLINA', dica: 'O carro bebe no posto.' },
      { texto: 'SOBREME_A', resposta: 'S', palavra: 'SOBREMESA', dica: 'O doce do fim do almoço.' },
      { texto: 'SURPRE_A', resposta: 'S', palavra: 'SURPRESA', dica: 'O que ninguém esperava na festa.' },
      { texto: 'PE_ADO', resposta: 'S', palavra: 'PESADO', dica: 'O contrário de leve.' },
      { texto: 'CA_ACO', resposta: 'S', palavra: 'CASACO', dica: 'Roupa de frio com mangas compridas.' },
      { texto: 'DEFE_A', resposta: 'S', palavra: 'DEFESA', dica: 'A parte do time que protege o gol.' },
      { texto: 'BRA_IL', resposta: 'S', palavra: 'BRASIL', dica: 'O nome do nosso país.' },
      { texto: 'RI_ADA', resposta: 'S', palavra: 'RISADA', dica: 'O barulho de quem acha graça.' },
      { texto: 'PESQUI_A', resposta: 'S', palavra: 'PESQUISA', dica: 'Procurar informação para aprender.' },
    ],
  },

  'l-u': {
    id: 'l-u',
    nome: 'L ou U',
    emoji: '🎩',
    nivel: 4,
    regra: 'No fim da sílaba, o som de U quase sempre se escreve com L (PAPEL, VOLTA). O U mesmo aparece em palavras como CHAPÉU e no passado dos verbos (CANTOU).',
    exemplo: 'PAPE_ → PAPEL',
    opcoes: ['L', 'U'],
    itens: [
      { texto: 'PAPE_', resposta: 'L', palavra: 'PAPEL', dica: 'A gente escreve e desenha nele.' },
      { texto: 'ANIMA_', resposta: 'L', palavra: 'ANIMAL', dica: 'O cachorro e a onça são exemplos.' },
      { texto: 'VO_TA', resposta: 'L', palavra: 'VOLTA', dica: 'Dar uma ___ no quarteirão.' },
      { texto: 'A_GUÉM', resposta: 'L', palavra: 'ALGUÉM', dica: 'Uma pessoa qualquer, não se sabe quem.' },
      { texto: 'BO_SA', resposta: 'L', palavra: 'BOLSA', dica: 'A mamãe leva na mão ou no ombro.' },
      { texto: 'FA_TA', resposta: 'L', palavra: 'FALTA', dica: 'Quando alguém não vem à aula.' },
      { texto: 'CA_DO', resposta: 'L', palavra: 'CALDO', dica: 'Sopa ralinha e quente.' },
      { texto: 'SO_DADO', resposta: 'L', palavra: 'SOLDADO', dica: 'Quem trabalha no quartel.' },
      { texto: 'AZU_', resposta: 'L', palavra: 'AZUL', dica: 'A cor do céu limpo.' },
      { texto: 'FUNI_', resposta: 'L', palavra: 'FUNIL', dica: 'Ajuda a passar o líquido para a garrafa.' },
      { texto: 'JORNA_', resposta: 'L', palavra: 'JORNAL', dica: 'Traz as notícias do dia.' },
      { texto: 'HOSPITA_', resposta: 'L', palavra: 'HOSPITAL', dica: 'Onde os médicos cuidam dos doentes.' },
      { texto: 'PINCE_', resposta: 'L', palavra: 'PINCEL', dica: 'Molha na tinta para pintar.' },
      { texto: 'CARACO_', resposta: 'L', palavra: 'CARACOL', dica: 'Bicho lento com a casinha em espiral.' },
      { texto: 'FUTEBO_', resposta: 'L', palavra: 'FUTEBOL', dica: 'Esporte de onze jogadores e uma bola.' },
      { texto: 'CA_MA', resposta: 'L', palavra: 'CALMA', dica: 'O contrário de nervosismo.' },
      { texto: 'MU_TA', resposta: 'L', palavra: 'MULTA', dica: 'O que o motorista paga quando corre demais.' },
      { texto: 'PA_CO', resposta: 'L', palavra: 'PALCO', dica: 'O lugar alto onde a peça acontece.' },
      { texto: 'SA_TO', resposta: 'L', palavra: 'SALTO', dica: 'O pulo do atleta.' },
      { texto: 'DIFÍCI_', resposta: 'L', palavra: 'DIFÍCIL', dica: 'O contrário de fácil.' },
      { texto: 'FÁCI_', resposta: 'L', palavra: 'FÁCIL', dica: 'O que a gente faz sem esforço.' },
      { texto: 'BRASI_', resposta: 'L', palavra: 'BRASIL', dica: 'O nome do nosso país.' },
      { texto: 'GO_FINHO', resposta: 'L', palavra: 'GOLFINHO', dica: 'Bicho esperto que salta no mar.' },
      { texto: 'CO_CHÃO', resposta: 'L', palavra: 'COLCHÃO', dica: 'Fica em cima da cama.' },
      { texto: 'SA_', resposta: 'L', palavra: 'SAL', dica: 'Deixa a comida salgada.' },
      { texto: 'MA_DADE', resposta: 'L', palavra: 'MALDADE', dica: 'O contrário de bondade.' },
      { texto: 'CHAPÉ_', resposta: 'U', palavra: 'CHAPÉU', dica: 'Cobre a cabeça e faz sombra no rosto.' },
      { texto: 'CÉ_', resposta: 'U', palavra: 'CÉU', dica: 'Fica lá em cima, com nuvens.' },
      { texto: 'CANTO_', resposta: 'U', palavra: 'CANTOU', dica: 'O que o passarinho fez ontem.' },
      { texto: 'PULO_', resposta: 'U', palavra: 'PULOU', dica: 'O que o sapo fez ontem.' },
      { texto: 'VÉ_', resposta: 'U', palavra: 'VÉU', dica: 'Tecido fininho que cobre o rosto da noiva.' },
      { texto: 'GRA_', resposta: 'U', palavra: 'GRAU', dica: 'A medida da temperatura.' },
      { texto: 'TROCO_', resposta: 'U', palavra: 'TROCOU', dica: 'O que ela fez ontem com a figurinha repetida.' },
      { texto: 'A_TOR', resposta: 'U', palavra: 'AUTOR', dica: 'Quem escreveu o livro.' },
      { texto: 'CA_SA', resposta: 'U', palavra: 'CAUSA', dica: 'O motivo de alguma coisa acontecer.' },
      { texto: 'PA_SA', resposta: 'U', palavra: 'PAUSA', dica: 'Uma paradinha no meio.' },
      { texto: 'JA_LA', resposta: 'U', palavra: 'JAULA', dica: 'A gaiola grande do leão.' },
      { texto: 'A_LA', resposta: 'U', palavra: 'AULA', dica: 'A hora de aprender na escola.' },
      { texto: 'FLA_TA', resposta: 'U', palavra: 'FLAUTA', dica: 'Instrumento de sopro cheio de furinhos.' },
      { texto: 'SA_DADE', resposta: 'U', palavra: 'SAUDADE', dica: 'O que se sente de quem está longe.' },
      { texto: 'TESO_RO', resposta: 'U', palavra: 'TESOURO', dica: 'Baú cheio de moedas de ouro.' },
    ],
  },
};

/** Os níveis da tela inicial, na ordem em que aparecem. */
export const niveis = [
  { numero: 1, titulo: 'Nível 1 — revisão', pacotes: ['m-n'] },
  { numero: 2, titulo: 'Nível 2', pacotes: ['r-rr', 's-ss'] },
  { numero: 3, titulo: 'Nível 3', pacotes: ['g-j', 'x-ch'] },
  { numero: 4, titulo: 'Nível 4 — desafio', pacotes: ['c-ss-s', 'l-u'] },
];
