import { montarCabecalho } from '../../shared/cabecalho.js';import { lancarConfete } from '../../shared/confete.js';import { nomeDaCrianca,obterConfiguracoes,registrarPartida } from '../../shared/progresso.js';import { tocar } from '../../shared/sons.js';import { configuracoes,encontrarConflitos,gerarSudoku,tabuleiroValido } from './jogo.js';
montarCabecalho('Sudoku de Emojis');const $=id=>document.getElementById(id),simbolos={4:['🐶','🐱','🐸','🦊'],6:['🐶','🐱','🐸','🦊','🐼','🐰'],9:['1','2','3','4','5','6','7','8','9']};let tamanho=Number(obterConfiguracoes().niveis.sudoku)||6,jogo,atual,fixas,ativa=null,dicas=0,inicio=0,intervalo=null;
function exibir(id){['inicio','partida','final'].forEach(t=>$(t).hidden=t!==id)}function selecionar(n){tamanho=Number(n);document.querySelectorAll('[data-nivel]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.nivel)===tamanho)))}for(const [n,cfg] of Object.entries(configuracoes)){const b=document.createElement('button');b.className='botao botao--neutro nivel';b.dataset.nivel=n;b.textContent=cfg.nome;b.addEventListener('click',()=>selecionar(n));$('niveis').append(b)}selecionar(configuracoes[tamanho]?tamanho:6);
function renderizar(){const cfg=configuracoes[tamanho],conflitos=encontrarConflitos(atual,tamanho),tab=$('tabuleiro');tab.style.gridTemplateColumns=`repeat(${tamanho},1fr)`;tab.replaceChildren();for(let l=0;l<tamanho;l++)for(let c=0;c<tamanho;c++){const b=document.createElement('button');b.className='celula';if(fixas[l][c])b.classList.add('fixa');if(ativa?.[0]===l&&ativa?.[1]===c)b.classList.add('ativa');if(conflitos.has(`${l}:${c}`))b.classList.add('conflito');if((c+1)%cfg.blocoColunas===0&&c<tamanho-1)b.classList.add('bloco-direita');if((l+1)%cfg.blocoLinhas===0&&l<tamanho-1)b.classList.add('bloco-baixo');b.textContent=atual[l][c]?simbolos[tamanho][atual[l][c]-1]:'';b.disabled=Boolean(fixas[l][c]);b.setAttribute('aria-label',`Linha ${l+1}, coluna ${c+1}${atual[l][c]?`, ${b.textContent}`:', vazia'}`);b.addEventListener('click',()=>{ativa=[l,c];renderizar()});tab.append(b)}}
function montarPaleta(){const p=$('paleta');p.replaceChildren();simbolos[tamanho].forEach((s,i)=>{const b=document.createElement('button');b.className='botao botao--neutro valor';b.textContent=s;b.setAttribute('aria-label',`Colocar ${s}`);b.addEventListener('click',()=>preencher(i+1));p.append(b)})}
function preencher(valor){if(!ativa){$('status').textContent='Escolha primeiro uma célula vazia.';return}atual[ativa[0]][ativa[1]]=valor;tocar('clique');renderizar();const conflitos=encontrarConflitos(atual,tamanho);$('status').textContent=conflitos.size?'Há um símbolo repetido. Tente corrigir!':'Tudo certo até aqui!';if(tabuleiroValido(atual))finalizar()}
function iniciarJogo(){jogo=gerarSudoku(tamanho);atual=jogo.tabuleiro.map(l=>[...l]);fixas=jogo.tabuleiro.map(l=>l.map(Boolean));ativa=null;dicas=0;$('dicas').textContent='0';$('status').textContent='Escolha uma célula vazia.';montarPaleta();renderizar();inicio=Date.now();clearInterval(intervalo);intervalo=setInterval(tempo,1000);tempo();exibir('partida');tocar('clique')}
function tempo(){const s=Math.floor((Date.now()-inicio)/1000);$('tempo').textContent=`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function darDica(){const vazias=[];for(let l=0;l<tamanho;l++)for(let c=0;c<tamanho;c++)if(!atual[l][c])vazias.push([l,c]);if(!vazias.length)return;ativa=vazias[Math.floor(Math.random()*vazias.length)];atual[ativa[0]][ativa[1]]=jogo.solucao[ativa[0]][ativa[1]];fixas[ativa[0]][ativa[1]]=true;dicas++;$('dicas').textContent=dicas;$('status').textContent='Uma célula foi preenchida para ajudar.';tocar('clique');renderizar();if(tabuleiroValido(atual))finalizar()}
function finalizar(){clearInterval(intervalo);const segundos=Math.max(1,Math.floor((Date.now()-inicio)/1000)),estrelas=dicas===0?3:dicas<=2?2:1;registrarPartida('sudoku',{acertos:jogo.removidas,erros:0,estrelas});$('resumo').textContent=`${nomeDaCrianca()}, você resolveu em ${Math.floor(segundos/60)} min ${segundos%60} s usando ${dicas} dica${dicas===1?'':'s'}.`;$('estrelas').textContent='⭐'.repeat(estrelas);exibir('final');tocar('vitoria');lancarConfete()}
$('comecar').addEventListener('click',iniciarJogo);$('dica').addEventListener('click',darDica);$('limpar').addEventListener('click',()=>preencher(0));$('sair').addEventListener('click',()=>{clearInterval(intervalo);exibir('inicio')});$('de-novo').addEventListener('click',iniciarJogo);$('trocar').addEventListener('click',()=>exibir('inicio'));document.addEventListener('keydown',e=>{if($('partida').hidden)return;const n=Number(e.key);if(n>=1&&n<=tamanho)preencher(n);if(e.key==='Backspace'||e.key==='Delete')preencher(0)});
