import { montarCabecalho } from '../../shared/cabecalho.js';
import { lancarConfete } from '../../shared/confete.js';
import { nomeDaCrianca, obterConfiguracoes, registrarPartida } from '../../shared/progresso.js';
import { estaMudo, tocar } from '../../shared/sons.js';
import { ampliarSequencia, estrelasPorRecorde } from './jogo.js';

montarCabecalho('Genius das Cores');
const $=id=>document.getElementById(id),CHAVE='jogos-elis:genius-recordes',frequencias={rosa:261.63,azul:329.63,verde:392,amarelo:523.25};
let modo=obterConfiguracoes().niveis.genius==='rapido'?'rapido':'calmo',sequencia=[],jogadas=[],aceitando=false,encerrado=false,audio=null;
const lerRecordes=()=>{try{return JSON.parse(localStorage.getItem(CHAVE)||'{}')}catch{return{}}};const salvarRecordes=r=>{try{localStorage.setItem(CHAVE,JSON.stringify(r))}catch{/* sem persistência */}};
function exibir(id){['inicio','partida','final'].forEach(t=>$(t).hidden=t!==id)}function selecionar(valor){modo=valor;document.querySelectorAll('[data-modo]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.modo===modo)));atualizarRecorde()}
function atualizarRecorde(){const r=lerRecordes()[modo]||0;$('recorde').textContent=`Recorde no modo ${modo==='calmo'?'Calmo':'Rápido'}: ${r}`;$('recorde-partida').textContent=r}
function nota(cor,duracao=.22){if(estaMudo())return;audio??=new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=frequencias[cor];g.gain.setValueAtTime(.12,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duracao);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duracao)}
const esperar=ms=>new Promise(r=>setTimeout(r,ms));async function acender(cor,duracao){const b=document.querySelector(`[data-cor="${cor}"]`);b.classList.add('acesa');nota(cor,duracao/1000);await esperar(duracao);b.classList.remove('acesa')}
async function mostrarSequencia(){aceitando=false;$('status').textContent='Observe!';document.querySelectorAll('.cor').forEach(b=>b.disabled=true);const velocidade=modo==='calmo'?520:Math.max(210,500-sequencia.length*22);await esperar(450);for(const cor of sequencia){if(encerrado)return;await acender(cor,velocidade*.62);await esperar(velocidade*.38)}jogadas=[];aceitando=true;document.querySelectorAll('.cor').forEach(b=>b.disabled=false);$('status').textContent='Sua vez!'}
async function proximaRodada(){sequencia=ampliarSequencia(sequencia);$('rodada').textContent=sequencia.length;await mostrarSequencia()}
async function jogar(cor){if(!aceitando)return;jogadas.push(cor);await acender(cor,170);if(jogadas[jogadas.length-1]!==sequencia[jogadas.length-1]){finalizar(false);return}if(jogadas.length===sequencia.length){aceitando=false;$('status').textContent='Muito bem!';tocar('acerto');await esperar(650);proximaRodada()}}
function iniciar(){if(!estaMudo()){audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume?.()}encerrado=false;sequencia=[];jogadas=[];exibir('partida');atualizarRecorde();tocar('clique');proximaRodada()}
function finalizar(parou=false){if(encerrado)return;encerrado=true;aceitando=false;document.querySelectorAll('.cor').forEach(b=>b.disabled=true);const pontos=Math.max(0,sequencia.length-1),recordes=lerRecordes(),anterior=recordes[modo]||0;if(pontos>anterior){recordes[modo]=pontos;salvarRecordes(recordes)}const estrelas=estrelasPorRecorde(pontos);registrarPartida('genius',{acertos:pontos,erros:parou?0:1,estrelas});$('resumo').textContent=`${nomeDaCrianca()}, você repetiu ${pontos} sequência${pontos===1?'':'s'} completa${pontos===1?'':'s'}!${pontos>anterior?' Novo recorde!':''}`;$('estrelas').textContent='⭐'.repeat(estrelas);exibir('final');if(pontos>=5){tocar('vitoria');lancarConfete()}else tocar(parou?'clique':'erro')}
document.querySelectorAll('[data-modo]').forEach(b=>b.addEventListener('click',()=>selecionar(b.dataset.modo)));document.querySelectorAll('.cor').forEach(b=>b.addEventListener('click',()=>jogar(b.dataset.cor)));$('comecar').addEventListener('click',iniciar);$('parar').addEventListener('click',()=>finalizar(true));$('de-novo').addEventListener('click',iniciar);$('trocar').addEventListener('click',()=>{exibir('inicio');atualizarRecorde()});selecionar(modo);
